[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "相册"
  url = "gallery"
  weight = 3

[[main]]
  parent = "gallery"
  name = "photo"
  url = "gallery/photo"

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4

[[main]]
  identifier = "contact"
  name = "反馈"
  url = "contact"
  weight = 5